### PR TITLE
Skip event update

### PR DESCRIPTION
**Pull request by boourns**
@bouk @lemonmade

this would let us skip subscriber notification when an action handler explicitly returns `false`.

I also fixed all the eslint/flow things, *except* the "expected method shorthand" is a problem.  Opening an issue on our eslint repo to discuss.

### CODE REVIEW

**Comment by bouk** [comment]
where does the skipping happen?

**Comment by boourns** [comment]
derp, good point @bouk. I already merged that part. This is just linter fixes :)

**Comment by boourns** [comment]
@bouk the notification skip is here
https://github.com/boourns/shux/commit/a3aed659e5c391e649f7a80fee1047986eb7a0db#diff-24d0c3b7cac36b9b55182f95ccf6759cR10

**Comment by lemonmade** [comment]
The skip should probably just check for falsiness, no? Changes here LGTM :+1:

**Comment by boourns** [comment]
@lemonmade I don't think so.

Since we don't run all reducers for all actions, we run the action methods directly, there's a greater chance for an action to care about why it's being called.  So generally I expect the action function will update something.  So I made the default functionality to notify subscribers, but possible to optimize if you return false.  I think that's very similar to react's convention - always rerender by default, unless `shouldComponentUpdate` is defined and returns false.

**Comment by lemonmade** [comment]
That makes sense, especially to keep in line with React. I think it might be best for shux to handle the state and do the smart checking of whether the object changed or not before notifying, which would circumvent the whole thing of having to manually specify anything. Thoughts?

**Comment by boourns** [comment]
"smart checking of whether the object changed or not"

From what i can tell, neither redux or flux has this because it is expensive to do deep object comparisons.  Flux forces you to call `_emitEvent` by hand, and redux actually calls every notifier after every action (!!)
https://github.com/rackt/redux/blob/master/src/createStore.js#L113-L120

However, we *could* do it by forcing our stores to use immutable.js, because we can tell if the object's changed.  What would you and @bouk think of that?

**Comment by lemonmade** [comment]
The reason redux calls every listener, every time is because the listeners have the smarts of when to actually update props and when not to (and listeners are minimized based on the convention of connecting very few things to the redux store).

**Comment by lemonmade** [comment]
(relevant code, from `react-redux`: https://github.com/rackt/react-redux/blob/a440b6ecdb1c0b4c6a707f3533f6ac7fdd643cd2/src/components/createConnect.js#L132-L149)

**Pull request merged**
